# Generated by Django 4.2.3 on 2023-08-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FakeDashboard",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fake_name", models.CharField(max_length=1)),
            ],
            options={
                "db_table": "fake_dashboards",
            },
        ),
    ]
