# Generated by Django 4.2.3 on 2023-08-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockDashboard",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fake_name", models.CharField(max_length=1)),
            ],
            options={
                "verbose_name": "dashboard",
                "db_table": "stock_dashboards",
            },
        ),
    ]
