# Generated by Django 4.2.3 on 2023-10-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FakeDashboard",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fake_name", models.CharField(max_length=1)),
            ],
            options={
                "verbose_name": "dashboard",
                "db_table": "fake_dashboards",
            },
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[],
            options={
                "verbose_name": "Dashboard",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("dashboards.fakedashboard",),
        ),
        migrations.CreateModel(
            name="InputPriceDashboard",
            fields=[],
            options={
                "verbose_name": "Input Price Dashboard",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("dashboards.fakedashboard",),
        ),
    ]
