# Generated by Django 4.2.3 on 2023-09-14 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stocks", "0006_stockhistorical"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomeStatement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ticker", models.CharField(max_length=10)),
                (
                    "time_range_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Yearly"), (2, "Quarterly")], default=1
                    ),
                ),
                ("time_value", models.CharField(max_length=50)),
                ("revenue", models.FloatField()),
                ("year_revenue_growth", models.FloatField()),
                ("quarter_revenue_growth", models.FloatField()),
                ("cost_of_good_sold", models.FloatField()),
                ("gross_profit", models.FloatField()),
                ("operation_expense", models.FloatField()),
                ("operation_profit", models.FloatField()),
                ("year_operation_profit_growth", models.FloatField()),
                ("quarter_operation_profit_growth", models.FloatField()),
                ("interest_expense", models.FloatField()),
                ("pre_tax_profit", models.FloatField()),
                ("post_tax_profit", models.FloatField()),
                ("share_holder_income", models.FloatField()),
                ("year_share_holder_income_growth", models.FloatField()),
                ("quarter_share_holder_income_growth", models.FloatField()),
                ("invest_profit", models.FloatField()),
                ("service_profit", models.FloatField()),
                ("other_profit", models.FloatField()),
                ("provision_expense", models.FloatField()),
                ("operation_income", models.FloatField()),
                ("ebitda", models.FloatField()),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_income_statement",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "db_table": "income_statements",
            },
        ),
        migrations.CreateModel(
            name="FinancialRatio",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ticker", models.CharField(max_length=10)),
                (
                    "time_range_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Yearly"), (2, "Quarterly")], default=1
                    ),
                ),
                ("time_value", models.CharField(max_length=50)),
                ("pe", models.FloatField()),
                ("pb", models.FloatField()),
                ("roe", models.FloatField()),
                ("roa", models.FloatField()),
                ("eps", models.FloatField()),
                ("book_value_per_share", models.FloatField()),
                ("interest_margin", models.FloatField()),
                ("non_interest_on_toi", models.FloatField()),
                ("bad_debt_percentage", models.FloatField()),
                ("provision_on_bad_debt", models.FloatField()),
                ("cost_of_financing", models.FloatField()),
                ("equity_on_total_asset", models.FloatField()),
                ("equity_on_loan", models.FloatField()),
                ("cost_to_income", models.FloatField()),
                ("equity_on_liability", models.FloatField()),
                ("eps_change", models.FloatField()),
                ("asset_on_equity", models.FloatField()),
                ("pre_provision_on_toi", models.FloatField()),
                ("post_tax_on_toi", models.FloatField()),
                ("loan_on_earn_asset", models.FloatField()),
                ("loan_on_asset", models.FloatField()),
                ("loan_on_deposit", models.FloatField()),
                ("deposit_on_earn_asset", models.FloatField()),
                ("bad_debt_on_asset", models.FloatField()),
                ("liquidity_on_liability", models.FloatField()),
                ("payable_on_equity", models.FloatField()),
                ("cancel_debt", models.FloatField()),
                ("book_value_per_share_change", models.FloatField()),
                ("credit_growth", models.FloatField()),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_financial_ratio",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "db_table": "financial_ratios",
            },
        ),
    ]
