# Generated by Django 4.2.3 on 2023-09-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financialratio",
            name="time_value",
        ),
        migrations.AddField(
            model_name="financialratio",
            name="quarter",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="financialratio",
            name="year",
            field=models.CharField(default="", max_length=10),
        ),
    ]
