# Generated by Django 4.2.3 on 2023-09-16 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0006_stockhistorical"),
        ("prices", "0002_remove_financialratio_time_value_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BalanceSheet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ticker", models.CharField(max_length=10)),
                (
                    "time_range_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Yearly"), (2, "Quarterly")], default=1
                    ),
                ),
                ("year", models.CharField(default="", max_length=10)),
                ("quarter", models.CharField(default="", max_length=10)),
                ("short_asset", models.FloatField()),
                ("cash", models.FloatField()),
                ("short_invest", models.FloatField()),
                ("short_receivable", models.FloatField()),
                ("inventory", models.FloatField()),
                ("long_asset", models.FloatField()),
                ("fixed_asset", models.FloatField()),
                ("asset", models.FloatField()),
                ("debt", models.FloatField()),
                ("short_debt", models.FloatField()),
                ("long_debt", models.FloatField()),
                ("equity", models.FloatField()),
                ("capital", models.FloatField()),
                ("central_bank_deposit", models.FloatField()),
                ("other_bank_deposit", models.FloatField()),
                ("other_bank_loan", models.FloatField()),
                ("stock_invest", models.FloatField()),
                ("customer_loan", models.FloatField()),
                ("bad_load", models.FloatField()),
                ("provision", models.FloatField()),
                ("net_customer_loan", models.FloatField()),
                ("other_asset", models.FloatField()),
                ("other_bank_credit", models.FloatField()),
                ("owe_other_bank", models.FloatField()),
                ("owe_central_bank", models.FloatField()),
                ("valuable_paper", models.FloatField()),
                ("payable_interest", models.FloatField()),
                ("receivable_interest", models.FloatField()),
                ("deposit", models.FloatField()),
                ("other_debt", models.FloatField()),
                ("fund", models.FloatField()),
                ("un_distributed_income", models.FloatField()),
                ("minor_share_holder_profit", models.FloatField()),
                ("payable", models.FloatField()),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_balance_sheet",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "db_table": "balance_sheets",
            },
        ),
    ]
