# Generated by Django 4.2.3 on 2023-09-19 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0006_stockhistorical"),
        ("prices", "0003_balancesheet"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsiderDeals",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ticker", models.CharField(max_length=10)),
                ("deal_announce_date", models.CharField(max_length=11)),
                ("deal_method", models.CharField(max_length=100)),
                ("deal_action", models.CharField(max_length=3)),
                ("deal_quantity", models.FloatField()),
                ("deal_price", models.FloatField()),
                ("deal_ratio", models.FloatField()),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_insider_deals",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "db_table": "company_insider_deals",
            },
        ),
    ]
