# Generated by Django 4.2.3 on 2023-09-19 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0006_stockhistorical"),
        ("prices", "0005_alter_insiderdeals_ticker"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialFlow",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ticker", models.CharField(max_length=10)),
                (
                    "time_range_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Yearly"), (2, "Quarterly")], default=1
                    ),
                ),
                ("year", models.CharField(default="", max_length=10)),
                ("quarter", models.CharField(default="", max_length=10)),
                ("invest_code", models.FloatField()),
                ("from_invest", models.FloatField()),
                ("from_financial", models.FloatField()),
                ("from_sale", models.FloatField()),
                ("free_cash_flow", models.FloatField()),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_flow",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "db_table": "financial_flows",
            },
        ),
    ]
