# Generated by Django 4.2.3 on 2023-10-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0006_financialflow"),
    ]

    operations = [
        migrations.CreateModel(
            name="InputPrice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(default="")),
                ("day", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                ("type", models.PositiveSmallIntegerField(db_index=True)),
                ("unit", models.CharField(max_length=100)),
                ("value", models.FloatField()),
            ],
            options={
                "db_table": "input_prices",
            },
        ),
    ]
