# Generated by Django 4.2.3 on 2023-10-10 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0007_inputprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputprice",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inputprice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
