# Generated by Django 4.2.3 on 2023-07-29 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("icb_code", models.CharField(max_length=4)),
                ("parent_id_level_1", models.CharField(max_length=4)),
                ("parent_id_level_2", models.CharField(max_length=4)),
                ("parent_id_level_3", models.CharField(max_length=4)),
                ("level", models.PositiveSmallIntegerField()),
            ],
            options={
                "db_table": "vn_stock_categories",
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=5)),
                ("name", models.CharField(max_length=500)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="stocks.stockcategory",
                    ),
                ),
            ],
            options={
                "db_table": "vn_stocks",
            },
        ),
    ]
