# Generated by Django 4.2.3 on 2023-07-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="code",
            field=models.CharField(max_length=10),
        ),
    ]
