# Generated by Django 4.2.3 on 2023-07-30 08:58

from django.db import migrations

from stocks.services.stock import StockService


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0002_alter_stock_code"),
    ]

    def reverse(apps, schema_editor):
        pass

    def import_vn_stock_category(apps, schema_editor):
        StockService.import_vn_stock_category()

    def import_vn_stock(apps, schema_editor):
        StockService.import_vn_stock()

    operations = [
        migrations.RunPython(import_vn_stock_category, reverse_code=reverse),
        migrations.RunPython(import_vn_stock, reverse_code=reverse),
    ]
