# Generated by Django 4.2.3 on 2023-07-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0003_migration_create_inital_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockDividendHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(db_index=True, max_length=10)),
                ("exercise_date", models.DateTimeField()),
                ("cash_year", models.PositiveSmallIntegerField()),
                ("cash_dividend_percentage", models.FloatField()),
                ("issue_method", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "vn_stock_dividend_histories",
            },
        ),
    ]
