# Generated by Django 4.2.3 on 2023-08-08 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0004_stockdividendhistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockdividendhistory",
            options={"verbose_name": "dividend historie"},
        ),
    ]
