# Generated by Django 4.2.3 on 2023-08-10 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0005_alter_stockdividendhistory_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockHistorical",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("close", models.FloatField()),
                ("volume", models.FloatField()),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_historical",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "db_table": "vn_stock_historical_data",
            },
        ),
    ]
