# Generated by Django 4.2.3 on 2023-08-15 07:55

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockDashboardBuilderTemplate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=500)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "dashboard template",
                "db_table": "stock_dashboard_builder_templates",
            },
        ),
        migrations.CreateModel(
            name="StockDashboardBuilderItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "chart_type",
                    models.PositiveSmallIntegerField(
                        choices=[(2, "Bar"), (5, "Line")], default=5
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#FF0000", image_field=None, max_length=18, samples=None
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="dashboard_builders.stockdashboardbuildertemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "dashboard builder item",
                "db_table": "stock_dashboard_builder_items",
            },
        ),
    ]
